config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  resources :articles do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  end_date   :date             not null
#  start_date :date             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :bigint           not null
#  user_id    :bigint
#
# Indexes
#
#  index_tasks_on_article_id  (article_id)
#  index_tasks_on_user_id     (user_id)
#
class Task < ApplicationRecord
  has_one_attached :eyecatch

  belongs_to :article
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validate :start_end_check

  def start_end_check
    errors.add(:end_date, 'cannot be registered before the Start date:(') unless self.start_date < self.end_date
  end

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def comment_count
    comments.count
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def show
    @article = Article.find(params[:article_id])
    @task = @article.tasks.find(params[:id])

    @comments = @task.comments
  end

  def new
    article = Article.find(params[:article_id])
    @task = article.tasks.build
    @task.user_id = current_user.id
  end

  def create
    article = Article.find(params[:article_id])
    @task = article.tasks.build(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to article_path(article), notice: 'Your task is saved!! ;)'
    else
      flash.now[:error] = 'Faild to save your task:('
      render :new
    end
  end

  def edit
    @article = Article.find(params[:article_id])
    @task = @article.tasks.find(params[:id])
  end

  def update
    @article = Article.find(params[:article_id])
    @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to article_path(@article), notice: 'Your task is updated!!'
    else
      flash.now[:error] = 'Faild to update your task:('
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @task = current_user.tasks.find(params[:id])
    if @task.destroy!
      redirect_to article_path(@article), notice: 'Success to delete your task'
    else
      flash.now[:error] = 'Faild to delete your task'
      render :show
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :start_date, :end_date, :eyecatch)
  end
end

app/views/tasks/edit.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @task, url: article_task_path(@task.article), local: true) do |f|
    %div
      = f.label :eyecatch, 'task eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :title, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :start_date, 'Start date'
    %div
      = f.datetime_select :start_date
    %div
      = f.label :end_date, 'End date'
    %div.end_date
      = f.datetime_select :end_date
    %div
    = f.submit 'Submit', class: 'btn-task'

app/views/tasks/index.html.haml
%h1 %Task

app/views/tasks/new.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @task, url: article_tasks_path(@task.article), local: true) do |f|
    %div
      = f.label :eyecatch, 'task eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :title, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :start_date, 'Start date'
    %div
      = f.datetime_select :start_date
    %div
      = f.label :end_date, 'End date'
    %div.end_date
      = f.datetime_select :end_date
    %div
    = f.submit 'Submit', class: 'btn-task'

app/views/tasks/show.html.haml
.container
  .task
    -if user_signed_in? && current_user.tasks.exists?(id: @task.id)
      .card_heart.dropdown
        = image_tag 'Combined Shape.png', class: 'dropbtn'
        .dropdown-content.mini
          = link_to edit_article_task_path(id: @task.id) do
            %p Edit
          = link_to 'Delete', article_task_path(id: @task.id), data: { method: 'delete', confirm: 'Are you sure to delete this task?' }
    .article_detail
      = image_tag @task.user.avatar_image
      %div
        %p= @task.author_name
        %p= @task.display_created_at
    %h1.article_title_task= @task.title
    - if @task.eyecatch.attached?
      .card_image_task
        = image_tag @task.eyecatch
    .article_content
      = @task.content
  .comment_title
    %p Comments
    - @comments.each do |comment|
      .task_comment
        = image_tag comment.user.avatar_image
        %div
          %p= comment.content
  = link_to new_article_task_comment_path(@article, @task) do
    .btn-secondary
      + Add a new comment