config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  resources :articles do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_task_id  (task_id)
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  has_one_attached :eyecatch

  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 100 }

  validates :content, presence: true
  validates :content, length: { minimum: 10 }
  validates :content, uniqueness: true

  belongs_to :user
  has_many :tasks, dependent: :destroy

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @tasks = @article.tasks
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: 'Saved!! ;)'
    else
      flash.now[:error] = 'Failed to save :('
      render :new
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: 'Updated!! ;)'
    else
      flash.now[:error] = 'Faild to update :('
      render :edit
    end
  end

  def destroy
    article = current_user.articles.find(params[:id])
    article.destroy!
    redirect_to root_path, notice: 'Successfully deleted :)'
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :eyecatch)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/views/articles/_article.html.haml
= link_to article_path(article) do
  .card
    - if article.eyecatch.attached?
      .card_image
        = image_tag article.eyecatch
    .card_content
      .card_title
        = article.title
        -if user_signed_in? && current_user.has_written?(article)
          .card_heart.dropdown
            = image_tag 'Combined Shape.png', class: 'dropbtn'
            .dropdown-content.mini
              = link_to edit_article_path(id: article.id) do
                %p Edit
              = link_to 'Delete', article_path(id: article.id), data: { method: 'delete', confirm: 'Are you sure to delete this board?' }
      .article_content
        = article.content
      .card_detail
        = image_tag article.user.avatar_image
        %div
          %p= article.author_name
          %p= article.display_created_at

app/views/articles/_form.html.haml
.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @article, local: true) do |f|
    %div
      = f.label :eyecatch, 'Board eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :title, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/articles/_tabs.html.haml
.tabs
  .tabs_item.active
    All Boards

app/views/articles/edit.html.haml
= render 'form', article: @article

app/views/articles/index.html.haml
.container
  = render 'tabs'
  - @articles.each do |article|
    = render 'article', article: article
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus
    .card
      .card_content.add_card
        %p + Add a new board

app/views/articles/new.html.haml
= render 'form', article: @article

app/views/articles/show.html.haml
.container
  - if @article.eyecatch.attached?
    .article_image
      =image_tag @article.eyecatch
  %h1.article_title= @article.title
  .article_detail
    = image_tag @article.user.avatar_image
    %div
      %p= @article.author_name
      %p= @article.display_created_at
  .article_content
    = @article.content
  - @tasks.each do |task|
    = link_to article_task_path(@article.id, task.id) do
      .card
        - if task.eyecatch.attached?
          .card_image
            = image_tag task.eyecatch
        .card_content
          .card_title
            = task.title
          .card_content
            = task.content
          .card_comment
            %span= task.comment_count
            = image_tag 'message-square-outline.png'
          .card_detail
            = image_tag task.user.avatar_image
  = link_to new_article_task_path(@article) do
    .card
      .card_content.add_card
        %p + Add a new card